name: Build

on: [workflow_dispatch, pull_request, push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install dependencies (linux)
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install libavformat-dev libavcodec-dev libavutil-dev
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install ffmpeg-shared
      shell: bash
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    - name: Linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}
        path: build/klient

